version: "3.8"

services:
  iyuuplus:
    image: iyuucn/iyuuplus-dev:latest
    container_name: iyuuplus
    network_mode: bridge
    restart: always
    ports:
      - ${wizard_port}:8780
    volumes:
      - ${TRIM_PKGETC}:/iyuu
      - ${TRIM_PKGVAR}/data:/data
